#!/usr/bin/env bash
# DISPLAYING BAD LUCK ON 4TH ITR AND GOOD LUCK ON 8TH ITR 

i=1

while ((i<=10))
do
	if ((i==4));then
		echo "bad luck"
	elif ((i==8));then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
